# 1.1 정수

In [1]:
# 정수를 나타내는데 필요한 바이트 수 나타내기
(999).bit_length()

10

In [2]:
s = '11'
d = int(s)
print(d)

11


In [3]:
b = int(s, 2)
print(b)

3


# 1.2 부동소수점

In [4]:
0.2 * 3 == 0.6

False

In [5]:
1.2 - 0.2 == 1.0

True

In [6]:
1.2 - 0.1 == 1.1

False

In [7]:
0.1 * 0.1 == 0.01

False

In [8]:
# 특정 소수점에서 동등성 비교
def a(x, y, places=7):
    return round(abs(x-y), places) == 0

In [9]:
# 몫과 나머지를 구하는 함수
divmod(45, 6)

(7, 3)

In [10]:
# 기본적으로 부동소수점 연산이 불가능
sum(0.1 for i in range(10)) == 1.0

False

In [11]:
# decimal 사용 시 정확도 있는 연산 가능
from decimal import Decimal
sum(Decimal("0.1") for i in range(10)) == Decimal("1.0")

True

In [12]:
# 2진수 문자열을 반환하는 함수
bin(999)

'0b1111100111'

In [13]:
# 8진수 문자열을 반환하는 함수
oct(999)

'0o1747'

In [14]:
# 16진수 문자열을 반환하는 함수
hex(999)

'0x3e7'

# 연습문제

## 다른 진법의 숫자를 10진수로 변환한다(2 ≤ base ≤ 10)

In [15]:
def convert_to_decimal(number, base):
    multiplier, result = 1, 0
    while number > 0:
        result += number % 10 * multiplier
        multiplier *= base
        number = number // 10
    return result

In [16]:
def test_convert_to_decimal():
    number, base = 1001, 2
    assert(convert_to_decimal(number, base) == 9)
    print('테스트 통과!')

In [17]:
test_convert_to_decimal()

테스트 통과!


## 10진수를 다른 진법의 숫자로 변환하는 함수(2 ≤ base ≤ 10)

In [18]:
def convert_from_decimal(number, base):
    multiplier, result = 1, 0
    while number > 0:
        result += number % base * multiplier
        multiplier *= 10
        number = number // base
    return result

In [19]:
def test_convert_from_decimal():
    number, base = 9, 2
    assert(convert_from_decimal(number, base) == 1001)
    print('테스트 통과!')

In [20]:
test_convert_from_decimal()

테스트 통과!


## 10진법 숫자를 20 이하의 진법으로 변환하는 함수

In [21]:
def convert_from_decimal_larger_bases(number, base):
    strings = "0123456789ABCDEFGHIJ"
    result = ""
    while number > 0:
        digit = number % base
        result = strings[digit] + result
        number = number // base
    return result

In [24]:
def test_convert_from_decimal_larger_bases():
    number, base = 31, 16
    assert(convert_from_decimal_larger_bases(number, base) == "1F")
    print("테스트 통과!")

In [25]:
test_convert_from_decimal_larger_bases()

테스트 통과!


## 재귀함수를 활용한 진법 변환

In [27]:
def convert_dec_to_any_base_rec(number, base):
    convertString = "0123456789ABCDEF"
    if number < base:
        return convertString[number]
    else:
        return convert_dec_to_any_base_rec(number // base, base) + convertString[number % base]

In [28]:
def test_convert_dec_to_any_base_rec():
    number = 9
    base = 2
    assert(convert_dec_to_any_base_rec(number, base) == "1001")
    print('테스트 통과!')

In [30]:
test_convert_dec_to_any_base_rec()

테스트 통과!


## EX5) 최대공약수 계산

In [31]:
# 단, (a > b)
def finding_gcd(a, b):
    while(b != 0):
        result = b
        a, b = b, a % b
    return result

In [32]:
def test_finding_gcd():
    number1 = 21
    number2 = 12
    assert(finding_gcd(number1, number2) == 3)
    print('테스트 통과!')

In [33]:
test_finding_gcd()

테스트 통과!


## random 모듈 예제

In [34]:
import random

def testing_random():
    '''random 모듈 테스트'''
    values = [1,2,3,4]
    print(random.choice(values))
    print(random.choice(values))
    print(random.choice(values))
    print(random.sample(values, 2))
    print(random.sample(values, 3))
    
    '''values 리스트를 섞는다.'''
    random.shuffle(values)
    print(values)
    
    '''0~10의 임의의 정수를 생성한다'''
    print(random.randint(0, 10))
    print(random.randint(0, 10))

In [35]:
testing_random()

3
4
4
[1, 2]
[1, 4, 3]
[4, 3, 2, 1]
9
9


## 피보나치 수열

In [37]:
import math

In [38]:
# 반복문을 이용 - 시간복잡도 O(n)
def find_fibonacci_seq_iter(n):
    if n < 2: return n
    a, b = 0, 1
    for i in range(n):
        a, b = b, a + b
    return a

In [39]:
# 재귀함수를 이용 - 시간복잡도 O(n^2)
def find_fibonacci_seq_rec(n):
    if n < 2: return n
    return find_fibonacci_seq_rec(n - 1) + find_fibonacci_seq_rec(n - 2)

In [40]:
# 수식을 이용 - 시간복잡도 O(n) (단, 70번째 이상부터 정확하지 않음)
def find_fibonacci_seq_form(n):
    sq5 = math.sqrt(5)
    phi = (1 + sq5) / 2
    return int(math.floor(phi ** n / sq5))

In [41]:
def test_find_fib():
    n = 10
    assert(find_fibonacci_seq_rec(n) == 55)
    assert(find_fibonacci_seq_iter(n) == 55)
    assert(find_fibonacci_seq_form(n) == 55)
    print("테스트 통과!")

In [42]:
test_find_fib()

테스트 통과!


In [45]:
# 제너레이터 활용한 피보나치 함수
def fib_generator():
    a, b = 0, 1
    while True:
        yield b
        a, b = b, a+b

In [46]:
fg = fib_generator()
for _ in range(10):
    print(next(fg), end=" ")

1 1 2 3 5 8 13 21 34 55 

## 소수 판별

In [47]:
import math
import random

In [48]:
# 브루트 포스를 이용한 함수
def finding_prime(number):
    num = abs(number)
    if num < 4 : return True
    for x in range(2, num):
        if num % x == 0:
            return False
    return True

In [50]:
# 제곱근의 성질을 이용한 함수
def finding_prime_sqrt(number):
    num = abs(number)
    if num < 4 : return True
    for x in range(2, int(math.sqrt(num)) + 1):
        if number % x == 0:
            return False
    return True

In [51]:
# 페르마의 소정리를 이용한 함수
'''페르마의 소정리 : p가 소수이고, a가 p의 배수가 아니면 a^(p-1) % p = 1'''
def finding_prime_fermat(number):
    if number <= 102:
        for a in range(2, number):
            if pow(a, number - 1, number) != 1:
                return False
        return True
    else:
        for i in range(100):
            a = random.randint(2, number - 1)
            if pow(a, number - 1, number) != 1:
                return False
        return True

In [53]:
def test_finding_prime():
    number1 = 17
    number2 = 20
    assert(finding_prime(number1) is True)
    assert(finding_prime(number2) is False)
    assert(finding_prime_sqrt(number1) is True)
    assert(finding_prime_sqrt(number2) is False)
    assert(finding_prime_fermat(number1) is True)
    assert(finding_prime_fermat(number2) is False)
    print("테스트 통과!")

In [54]:
test_finding_prime()

테스트 통과!


## 넘파이 패키지

In [59]:
import numpy as np

In [60]:
np.array( ((11,12,13), (21,22,23), (31,32,33)) )

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [61]:
x = np.array( ((11,12,13), (21,22,23)) )

In [62]:
x.ndim

2

In [64]:
def testing_numpy():
    '''tests many features of numpy'''
    ax = np.array([1,2,3])
    ay = np.array([3,4,5])
    print(ax)
    print(ax*2)
    print(ax+10)
    print(np.sqrt(ax))
    print(np.cos(ax))
    print(ax-ay)
    print(np.where(ax<2, ax, 10))
    
    m = np.matrix([ax, ay, ax])
    print(m)
    print(m.T)
    
    grid1 = np.zeros(shape=(10,10), dtype=float)
    grid2 = np.zeros(shape=(10,10), dtype=float)
    print(grid1)
    print(grid2)
    print(grid1[1]+10)
    print(grid2[:, 2]*2)

In [65]:
testing_numpy()

[1 2 3]
[2 4 6]
[11 12 13]
[1.         1.41421356 1.73205081]
[ 0.54030231 -0.41614684 -0.9899925 ]
[-2 -2 -2]
[ 1 10 10]
[[1 2 3]
 [3 4 5]
 [1 2 3]]
[[1 3 1]
 [2 4 2]
 [3 5 3]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [66]:
import numpy
import time

In [67]:
def trad_version():
    t1 = time.time()
    X = range(10000000)
    Y = range(10000000)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1

In [68]:
def numpy_version():
    t1 = time.time()
    X = numpy.arange(10000000)
    Y = numpy.arange(10000000)
    Z = X + Y
    return time.time() - t1

In [69]:
print(trad_version())
print(numpy_version())

3.2839503288269043
0.06205582618713379
